INSERT INTO ratings (beer_id,author,value) VALUES ('maryensztadt craft brewery|summertime papaja, mango & brzoskwinia|fruit ale','Dawid',1.0) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('browar za miastem|dobry moment|fruit ale','Dawid',3.0) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('browar za miastem|dobry moment|fruit ale','Jastrząb',1.75) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('trzech kumpli|lager wiedeński|lager wiedeński','Dawid',2.0) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('magic road|mochi green - kiwi, banana & mochi|pastry sour','Dawid',3.5) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('magic road|mochi green - kiwi, banana & mochi|pastry sour','Jastrząb',1.75) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('browar gościszewo|ogród mistrza witbier z tymiankiem cytrynowym|witbier','Dawid',1.25) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('browar gościszewo|ogród mistrza witbier z tymiankiem cytrynowym|witbier','Jastrząb',2.75) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('browar stu mostów|berry up! strawberry | rasberry | coconut|pastry sour','Dawid',4.5) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('browar stu mostów|berry up! strawberry | rasberry | coconut|pastry sour','Jastrząb',3.75) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('pinta|mild classic|ciemne','Dawid',2.0) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('funky fluid|gelato purple fluff|ice cream sour','Dawid',4.0) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('funky fluid|gelato purple fluff|ice cream sour','Jastrząb',3.5) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('pinta|summer beer supply|polish cold ipa','Dawid',1.25) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('nepo|smoothie bowl sweet morning cherry cheesecake|pastry sour','Dawid',2.5) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('amber|po godzinach | graff|graff','Dawid',3.0) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('amber|po godzinach | graff|graff','Jastrząb',1.0) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('browar za miastem|wolny wieczór|fruit ale','Dawid',2.0) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('browar za miastem|wolny wieczór|fruit ale','Jastrząb',3.25) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('bojan|bananowe|owocowe','Dawid',2.0) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('bojan|bananowe|owocowe','Jastrząb',3.25) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('browar zakładowy|sokowirówka – kwaśne ale z malinami i jagodami|sour ale','Dawid',1.5) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('browar zakładowy|sokowirówka – kwaśne ale z malinami i jagodami|sour ale','Jastrząb',1.25) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('funky fluid|farm ''26 to glass citra|hop selection neipa','Dawid',2.5) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('funky fluid|farm ''26 to glass citra|hop selection neipa','Jastrząb',3.0) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('browar zakładowy|hiszpańskie wakakcje|pastry sour','Dawid',2.5) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('browar zakładowy|hiszpańskie wakakcje|pastry sour','Jastrząb',3.25) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('browar zakładowy|wyjąć grill to jest chwila|new zeland west coast ipa','Dawid',2.0) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('browar zakładowy|wyjąć grill to jest chwila|new zeland west coast ipa','Jastrząb',1.75) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('litovel|cerny citron|pełne cytrynowe','Dawid',4.0) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('litovel|cerny citron|pełne cytrynowe','Jastrząb',4.0) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('pinta|summer beer supply|modern west coast ipa','Jastrząb',1.5) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('bojan|kwaśna marakuja|sour','Jastrząb',1.75) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('inne beczki|hopgang aurora|northern ipa','Jastrząb',2.25) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('funky fluid|farm ''26 to glass mosaic|hop selection neipa','Jastrząb',3.0) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('pinta|summer beer supply|session hazy ipa','Jastrząb',1.75) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('funky fluid|farm ''26 to glass simcoe|hop selection neipa','Jastrząb',1.5) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('guiness||stout','Jastrząb',5.0) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('guiness||stout','MlodyD',5.0) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('guiness||stout','zaskurio de lima',5.0) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO ratings (beer_id,author,value) VALUES ('grupa żywiec|królewskie|jasne','Koneser',5.0) ON CONFLICT(beer_id,author) DO UPDATE SET value=excluded.value;
INSERT INTO comments (beer_id,author,text,date) VALUES ('litovel|cerny citron|pełne cytrynowe','Jastrząb','No przepyszny jest, może i dla kobiet w ciąży ale orzeźwiający i daje Liptonem','22.07.2026');
INSERT INTO comments (beer_id,author,text,date) VALUES ('guiness||stout','MlodyD','Komentarz zbędny','20.07.2026');
INSERT INTO comments (beer_id,author,text,date) VALUES ('guiness||stout','zaskurio de lima','Bardzo duzy plus jest taki, ze trzeba zamowic tak duzo az uda sie split the g','20.07.2026');
INSERT INTO comments (beer_id,author,text,date) VALUES ('grupa żywiec|królewskie|jasne','Koneser','Doskonała jakość i smak, szczególnie ciepły w puszce','20.07.2026');
